; ============== PC BUILDS ==============

[base_env_pc]
platform = native
build_flags =
    -std=c++20
    -O3
    -Werror
		-lsfml-graphics
		-lsfml-audio
    -lsfml-window
    -lsfml-system
lib_ignore = esp32version

[env:pc_build]
extends = base_env_pc
build_src_filter = +<main_pc.cpp>



; ============== ESP32 BUILDS ==============

[my_board]
board = esp-wrover-kit

[new_board]
board = esp32-s3-devkitc-1
board_build.arduino.memory_type = qio_qspi 
board_build.flash_mode = qio
board_build.psram_type = qio
board_upload.flash_size = 8MB
board_upload.maximum_size = 8388608
board_build.partitions = default_8MB.csv


[base_env_esp32]
platform = espressif32
extends = new_board
monitor_speed = 115200
framework = arduino
lib_ignore = pcversion
monitor_filters = esp32_exception_decoder
build_flags = 
	-O3
	-std=gnu++2a ; Use C++20
	-D BOARD_HAS_PSRAM
	-Werror
	; -mfix-esp32-psram-cache-issue
build_unflags = -std=gnu++11



[env:esp32_build]
extends = base_env_esp32
build_src_filter = +<main_esp32.cpp>


[env:esp32_test]
extends = base_env_esp32
test_build_src = yes
build_src_filter = +<main_esp32_test.cpp>